name: Demo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Demo'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use nightly Rust
        run: rustup default nightly
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-bindgen CLI
        run: cargo install wasm-bindgen-cli --version 0.2.93
      - name: Build demo
        run: cargo build -p mxmlextrema_as3parser_demo --release --target wasm32-unknown-unknown
      - name: Update demo/dist
        run: wasm-bindgen --target web --out-dir demo/dist target/wasm32-unknown-unknown/release/mxmlextrema_as3parser_demo.wasm
      - name: Git commit report
        run: |
          git config --global user.name 'hydroperfox'
          git config --global user.email 'hydroperfox@gmail.com'
          git switch -C demo
          git rm --cached -r .
          git add demo
          git rm --cached -r demo/src
          git rm --cached demo/Cargo.toml
          git commit -m "Automated report"
          git push origin -f demo
